### ISSUE TITLE
Incompatibility with InvMove mod

### ISSUE THREAD

**Issue by JustNerro** [CIOCOLATA47/AutoWalk#3]
**Describe the bug**
Incompatibility with InvMove mod.
https://modrinth.com/mod/invmove
when opening the Inventory, player stops moving even with autowalk enabled

**To Reproduce**
activate AutoWalk, open inventory

**Expected Behavior**
I continue walking automatically in the background

**What happens instead**
I stop walking, pressing WASD manually still works though

**Comment by CIOCOLATA47** [comment]
Imma look into it and fix
